export const productAdidas = [
  { id: "adidas-1", img: "/shoes/adidas/s1.avif", brand: "ADIDAS", desc: "Adidas Ultraboost Light Running Shoes", price: 2600, oldPrice: 5200, discount: "50%" },
  { id: "adidas-2", img: "/shoes/adidas/s2.avif", brand: "ADIDAS", desc: "Adidas Adizero Boston 12 Shoes", price: 2800, oldPrice: 5600, discount: "50%" },
  { id: "adidas-3", img: "/shoes/adidas/s3.avif", brand: "ADIDAS", desc: "Adidas Duramo SL Lightweight Trainers", price: 2400, oldPrice: 4800, discount: "50%" },
  { id: "adidas-4", img: "/shoes/adidas/s4.avif", brand: "ADIDAS", desc: "Adidas Supernova Rise Running Shoes", price: 3000, oldPrice: 6000, discount: "50%" },
  { id: "adidas-5", img: "/shoes/adidas/s5.avif", brand: "ADIDAS", desc: "Adidas Solar Glide 6 Performance Shoes", price: 2700, oldPrice: 5400, discount: "50%" },
  { id: "adidas-6", img: "/shoes/adidas/s6.avif", brand: "ADIDAS", desc: "Adidas Adizero Prime X 2 Strung Shoes", price: 3200, oldPrice: 6400, discount: "50%" },
  { id: "adidas-7", img: "/shoes/adidas/s7.avif", brand: "ADIDAS", desc: "Adidas RunFalcon 3.0 Everyday Trainers", price: 2500, oldPrice: 5000, discount: "50%" },
  { id: "adidas-8", img: "/shoes/adidas/s8.avif", brand: "ADIDAS", desc: "Adidas Galaxy 6 Road Running Shoes", price: 2600, oldPrice: 5200, discount: "50%" },
  { id: "adidas-9", img: "/shoes/adidas/s9.avif", brand: "ADIDAS", desc: "Adidas Terrex Swift R3 Hiking Shoes", price: 2900, oldPrice: 5800, discount: "50%" },
  { id: "adidas-10", img: "/shoes/adidas/s10.avif", brand: "ADIDAS", desc: "Adidas Racer Adapt Lifestyle Sneakers", price: 3100, oldPrice: 6200, discount: "50%" },
  { id: "adidas-11", img: "/shoes/adidas/s11.avif", brand: "ADIDAS", desc: "Adidas Adizero Takumi Sen 9 Shoes", price: 3000, oldPrice: 6000, discount: "50%" },
  { id: "adidas-12", img: "/shoes/adidas/s12.avif", brand: "ADIDAS", desc: "Adidas Samba OG Classic Sneakers", price: 2800, oldPrice: 5600, discount: "50%" },
  { id: "adidas-13", img: "/shoes/adidas/s13.avif", brand: "ADIDAS", desc: "Adidas Gazelle Retro Lifestyle Sneakers", price: 2700, oldPrice: 5400, discount: "50%" },
  { id: "adidas-14", img: "/shoes/adidas/s14.avif", brand: "ADIDAS", desc: "Adidas Superstar Classic White Shoes", price: 3200, oldPrice: 6400, discount: "50%" },
  { id: "adidas-15", img: "/shoes/adidas/s15.avif", brand: "ADIDAS", desc: "Adidas Stan Smith Premium Sneakers", price: 3000, oldPrice: 6000, discount: "50%" },
  { id: "adidas-16", img: "/shoes/adidas/s16.avif", brand: "ADIDAS", desc: "Adidas NMD R1 Lifestyle Running Shoes", price: 2900, oldPrice: 5800, discount: "50%" },
  { id: "adidas-17", img: "/shoes/adidas/s17.avif", brand: "ADIDAS", desc: "Adidas Forum Low Basketball Sneakers", price: 3100, oldPrice: 6200, discount: "50%" },
  { id: "adidas-18", img: "/shoes/adidas/s18.avif", brand: "ADIDAS", desc: "Adidas ZX 22 Boost Casual Sneakers", price: 2800, oldPrice: 5600, discount: "50%" },
  { id: "adidas-19", img: "/shoes/adidas/s19.avif", brand: "ADIDAS", desc: "Adidas Predator Accuracy Football Shoes", price: 3200, oldPrice: 6400, discount: "50%" },
  { id: "adidas-20", img: "/shoes/adidas/s20.avif", brand: "ADIDAS", desc: "Adidas X Speedportal.3 Turf Soccer Shoes", price: 3000, oldPrice: 6000, discount: "50%" },
];
